name: genet
channels:
  - anaconda
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - absl-py
  - astor
  - biopython
  - cudatoolkit
  - cudnn
  - cupti
  - decorator
  - gast
  - grpcio
  - h5py
  - hdf5
  - intel-openmp
  - ipython
  - ipython_genutils
  - jedi
  - libedit
  - libffi
  - libgcc
  - libgcc-ng
  - libgfortran-ng
  - libprotobuf
  - libstdcxx-ng
  - mkl
  - ncurses
  - parso
  - pexpect
  - pickleshare
  - prompt_toolkit
  - ptyprocess
  - pygments
  - pyyaml
  - readline
  - simplegeneric
  - sqlite
  - termcolor
  - tk
  - traitlets
  - wcwidth
  - yaml
  - zlib
  - bcftools
  - htslib
  - pysam
  - samtools
  - backports
  - backports.weakref
  - bleach
  - bzip2
  - ca-certificates
  - certifi
  - curl
  - cycler
  - dbus
  - expat
  - fontconfig
  - freetype
  - funcsigs
  - gettext
  - glib
  - gst-plugins-base
  - gstreamer
  - html5lib
  - icu
  - jpeg
  - kiwisolver
  - krb5
  - libiconv
  - libpng
  - libssh2
  - libxcb
  - libxml2
  - matplotlib
  - mkl_fft
  - mkl_random
  - mock
  - openblas
  - openssl
  - pbr=3.1.1
  - pcre
  - pip
  - protobuf
  - pyparsing
  - pyqt
  - python-dateutil
  - pytz
  - qt
  - setuptools
  - sip
  - six
  - tornado
  - tqdm
  - webencodings
  - werkzeug
  - wheel
  - xorg-libxau
  - xorg-libxdmcp
  - xz
  - blas
  - libgfortran
  - markdown
  - numpy
  - python
  - scikit-learn
  - scipy
  - tensorboard
  - tensorflow-gpu
  - tensorflow-gpu-base
  - tensorflow-tensorboard
  - pip:
    - appdirs
    - autograd
    - biolib
    - chardet
    - comparem
    - future
    - idna
    - nanosim-h
    - ncbi-genome-download
    - progressbar2
    - psutil
    - pyarrow
    - python-utils
    - pyzmq
    - requests
    - tabulate
    - tensorflow
    - tensorpack
    - treelib
    - urllib3

